### ISSUE TITLE
moondream1 model support

### ISSUE THREAD

**Issue by questsin** [ollama/ollama#2462]
how to port the tiny vision model at https://huggingface.co/vikhyatk/moondream1 
 with Tensor type FP16 using SigLIP, Phi-1.5 and the LLaVa training dataset, to ollama for local ubuntu execution
 moondream uses the following python3 libraries 
 -  accelerate==0.25.0
 - huggingface-hub==0.20.1
 - Pillow==10.1.0
 - torch==2.1.2
 - torchvision==0.16.2
 - transformers==4.36.2
 - einops==0.7.0
 - gradio==4.15.0
 - timm==0.9.12

```bash
gh repo clone ollama/ollama
cd ollama
git submodule init
git submodule update llm/llama.cpp

sudo apt install python3.11-venv

python3 -m venv llm/llama.cpp/.venv
source llm/llama.cpp/.venv/bin/activate
pip install -r llm/llama.cpp/requirements.txt

make -C llm/llama.cpp quantize
sudo apt-get install git-lfs
git lfs install
# git clone https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1 model
git clone https://huggingface.co/vikhyatk/moondream1
git lfs pull

# python3 llm/llama.cpp/convert.py ./model --outtype f16 --outfile converted.bin
python3 llm/llama.cpp/convert-hf-to-gguf.py ./model --outtype f16 --outfile converted.bin

# Error output bellow
# Loading model: model
# Traceback (most recent call last):
#   File "/home/questsin/repo/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 1612, in <module>
#     main()
#   File "/home/questsin/repo/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 1593, in main
#     model_instance = model_class(dir_model, ftype_map[args.outtype], fname_out, args.bigendian)
#                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/questsin/repo/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 57, in __init__
#     self.model_arch = self._get_model_architecture()
#                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "/home/questsin/repo/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 262, in _get_model_architecture
#     raise NotImplementedError(f'Architecture "{arch}" not supported!')
# NotImplementedError: Architecture "Moondream" not supported!
```

**Comment by jmorganca** [comment]
Merging with #2259

**Comment by Kreijstal** [comment]
could moondream2 be done too?

**Comment by Seedmanc** [comment]
A year passed.
