### ISSUE TITLE
Conversion Script

### ISSUE THREAD

**Issue by scefali** [ollama/ollama#3543]
### What is the issue?

I am trying to run the conversion script as shown in the example for conversion to gguf.

### What did you expect to see?

```
python llm/llama.cpp/convert.py ./model --outtype f16 --outfile converted.bin           

Loading model file model/model-00001-of-00002.safetensors
Traceback (most recent call last):
  File "/Users/stevecefali/omoide/ollama/llm/llama.cpp/convert.py", line 1523, in <module>
    main()
  File "/Users/stevecefali/omoide/ollama/llm/llama.cpp/convert.py", line 1455, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevecefali/omoide/ollama/llm/llama.cpp/convert.py", line 1344, in load_some_model
    models_plus.append(lazy_load_file(path))
                       ^^^^^^^^^^^^^^^^^^^^
  File "/Users/stevecefali/omoide/ollama/llm/llama.cpp/convert.py", line 966, in lazy_load_file
    raise ValueError(f"unknown format: {path}")
ValueError: unknown format: model/model-00001-of-00002.safetensors
```

### Steps to reproduce

```
git clone git@github.com:ollama/ollama.git ollama
cd ollama
git submodule init
git submodule update llm/llama.cpp
python3 -m venv llm/llama.cpp/.venv
source llm/llama.cpp/.venv/bin/activate
pip install -r llm/llama.cpp/requirements.txt
make -C llm/llama.cpp quantize
git lfs install
git clone https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1 model
python llm/llama.cpp/convert.py ./model --outtype f16 --outfile converted.bin
```

**Comment by pdevine** [comment]
@scefali what model are you trying to convert? You probably want to use `convert-hf-to-gguf.py` if you're converting from safetensors.
