### ISSUE TITLE
Multi language embedding

### ISSUE THREAD

**Issue by wouterverduin** [ollama/ollama#3747]
Hi all from Ollama!

First off: Great work with Ollama, keep up the good work!

What i am missing though is models in different languages (dutch for me personally). Is it possible to add multilingual embeddings like "intfloat/multilingual-e5-large-instruct"?

If there is a way to do this myself i would love the directions! 

Thanks in advance!

**Comment by FidelCastillo** [comment]
Is possible to use this Bert model in ollama?

jinaai/jina-embeddings-v2-base-es

**Comment by thinkverse** [comment]
> Is possible to use this Bert model in ollama?
> 
> 
> 
> jinaai/jina-embeddings-v2-base-es

No because JinaAI uses a modified version of Bert they created called JinaBert and that architecture currently isn't supported.

**Comment by dcasota** [comment]
@thinkverse Actually there is no much choice. E.g. `mxbai-embed-large` is listed, however in `examples/langchain-python-rag-privategpt/ingest.py` and `privateGPT.py` it cannot be used, because the api path isn't in /sentence-transformers.
On the same hand, `paraphrase-multilingual-MiniLM-L12-v2` would be very nice as embeddings_model as it allows 50 languages, but the [model](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2) not listed in https://ollama.com/blog/embedding-models . The architecture is declared as BertModel and the api path in /sentence-transformers would fit, too.

**Comment by YuryAlsheuski** [comment]
Hi, I tried to convert `paraphrase-multilingual-MiniLM-L12-v2` to gguf like:
`python /root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py ./paraphrase-multilingual-MiniLM-L12-v2 --outtype f16 --outfile paraphrase-multilingual-MiniLM-L12-v2.gguf` but have the next trace:

Loading model: paraphrase-multilingual-MiniLM-L12-v2
gguf: This GGUF file is for Little Endian only
Set model parameters
gguf: context length = 512
gguf: embedding length = 384
gguf: feed forward length = 1536
gguf: head count = 12
gguf: layer norm epsilon = 1e-12
gguf: file type = 1
Set model tokenizer
Traceback (most recent call last):
  File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 3001, in <module>
    main()
  File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2988, in main
    model_instance.set_vocab()
  File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2530, in set_vocab
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 238, in get_vocab_base
    tokenizer = AutoTokenizer.from_pretrained(self.dir_model)
  File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 880, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2292, in _from_pretrained
    tokenizer_file_handle = json.load(tokenizer_file_handle)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

So, do we have opportunities to convert and use it manually? Thanks!

**Comment by kilmarnock** [comment]
the model jina/jina-embeddings-v2-base-de is now downloadable from the ollama model list. It uses a jina-bert-v2 architecture. Unfortunately, this architecture is not supported in ollama v.0.1.38:

llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'jina-bert-v2'

**Comment by thinkverse** [comment]
> the model jina/jina-embeddings-v2-base-de is now [downloadable](https://ollama.com/jina/jina-embeddings-v2-base-de) from the ollama model list. It uses a jina-bert-v2 architecture. Unfortunately, this architecture is not supported in ollama v.0.1.38:

The PR to update the llama.cpp backend hasn't yet been merged - https://github.com/ollama/ollama/pull/4414, hopefully in v0.1.39.

**Comment by JoanFM** [comment]
> the model jina/jina-embeddings-v2-base-de is now [downloadable](https://ollama.com/jina/jina-embeddings-v2-base-de) from the ollama model list. It uses a jina-bert-v2 architecture. Unfortunately, this architecture is not supported in ollama v.0.1.38:
> 
> llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'jina-bert-v2'
> 
> However it claims
> 
> > Ollama Usage
> > This model is an embedding model, meaning it can only be used to generate embeddings.
> 
> > You can get it by doing ollama pull jina/jina-embeddings-v2-base-de

Hey @kilmarnock,

This is my fault that I pushed the model with the documentation too early.

We are waiting for the mentioned PR to be merged and released.

Once it is done I will update the docs with the minimum version needed.

@FidelCastillo this also applies for the Spanish model!

**Comment by dcasota** [comment]
> Hi @dcasota, @thinkverse! I tried to convert `paraphrase-multilingual-MiniLM-L12-v2` to gguf like: `python /root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py ./paraphrase-multilingual-MiniLM-L12-v2 --outtype f16 --outfile paraphrase-multilingual-MiniLM-L12-v2.gguf` but have the next trace:
> 
> Loading model: paraphrase-multilingual-MiniLM-L12-v2 gguf: This GGUF file is for Little Endian only Set model parameters gguf: context length = 512 gguf: embedding length = 384 gguf: feed forward length = 1536 gguf: head count = 12 gguf: layer norm epsilon = 1e-12 gguf: file type = 1 Set model tokenizer Traceback (most recent call last): File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 3001, in main() File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2988, in main model_instance.set_vocab() File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2530, in set_vocab tokens, toktypes, tokpre = self.get_vocab_base() File "/root/.ollama/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 238, in get_vocab_base tokenizer = AutoTokenizer.from_pretrained(self.dir_model) File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 880, in from_pretrained return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained return cls._from_pretrained( File "/root/.ollama/ollama/llm/llama.cpp/.venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2292, in _from_pretrained tokenizer_file_handle = json.load(tokenizer_file_handle) File "/usr/lib/python3.10/json/**init**.py", line 293, in load return loads(fp.read(), File "/usr/lib/python3.10/json/**init**.py", line 346, in loads return _default_decoder.decode(s) File "/usr/lib/python3.10/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> So, do we have opportunities to convert and use it manually? Thanks!

Unfortunately, I didn't check the llama.cpp version at that time. The latest ollama bits and `python3.11 convert-hf-to-gguf.py --outtype f32 ./paraphrase-multilingual-MiniLM-L12-v2/ --outfile ./models/paraphrase-multilingual-MiniLM-L12-v2.gguf` fail with

```
(.venv) dcaso [ ~/ollama/examples/langchain-python-rag-privategpt/llama.cpp ]$ python3.11 convert-hf-to-gguf.py --outtype f32 ./paraphrase-multilingual-MiniLM-L12-v2/ --outfile ./models/paraphrase-multilingual-MiniLM-L12-v2.gguf
INFO:hf-to-gguf:Loading model: paraphrase-multilingual-MiniLM-L12-v2
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:gguf: context length = 512
INFO:hf-to-gguf:gguf: embedding length = 384
INFO:hf-to-gguf:gguf: feed forward length = 1536
INFO:hf-to-gguf:gguf: head count = 12
INFO:hf-to-gguf:gguf: layer norm epsilon = 1e-12
INFO:hf-to-gguf:gguf: file type = 0
INFO:hf-to-gguf:Set model tokenizer
Traceback (most recent call last):
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/llama.cpp/convert-hf-to-gguf.py", line 2546, in <module>
    main()
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/llama.cpp/convert-hf-to-gguf.py", line 2531, in main
    model_instance.set_vocab()
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/llama.cpp/convert-hf-to-gguf.py", line 2072, in set_vocab
    tokens, toktypes, tokpre = self.get_vocab_base()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/llama.cpp/convert-hf-to-gguf.py", line 377, in get_vocab_base
    tokenizer = AutoTokenizer.from_pretrained(self.dir_model)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 880, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dcaso/ollama/examples/langchain-python-rag-privategpt/.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2292, in _from_pretrained
    tokenizer_file_handle = json.load(tokenizer_file_handle)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(.venv) dcaso [ ~/ollama/examples/langchain-python-rag-privategpt/llama.cpp ]$
```

**Comment by stringang** [comment]
after a long time of struggling, I found that it is not supported.

**Comment by YuryAlsheuski** [comment]
In any case, it would be great if paraphrase-multilingual-MiniLM-L12-v2 will be supported with manual importing at least. Currently, it is pretty popular. Thanks!

**Comment by dcasota** [comment]
@YuryAlsheuski With an older branch of llama.cpp, the manual import seems to work
```
sudo tdnf install -y git-lfs git
git lfs install

git clone -b b2536 https://github.com/ggerganov/llama.cpp.git
cd llama.cpp
pip3 install -r requirements.txt

# paraphrase-multilingual-MiniLM-L12-v2
export Model=paraphrase-multilingual-MiniLM-L12-v2
export HuggingFacePath=https://huggingface.co/sentence-transformers
git clone $HuggingFacePath/$Model
python3 convert-hf-to-gguf.py ./$Model --outfile ./models/$Model.gguf --outtype f32

cd models
sudo cat <<EOF | sudo tee ./Modelfile
FROM ./paraphrase-multilingual-MiniLM-L12-v2.gguf
EOF
ollama create paraphrase-multilingual-MiniLM-L12-v2 -f ./Modelfile
cd ..
cd ..
```

**Comment by thinkverse** [comment]
> it would be great if paraphrase-multilingual-MiniLM-L12-v2 will be supported

One user has uploaded it to the registry already: https://ollama.com/nextfire/paraphrase-multilingual-minilm, haven't tested it so I cannot speak on its performance.

**Comment by thinkverse** [comment]
> Is possible to use this Bert model in ollama?
> 
> jinaai/jina-embeddings-v2-base-es

The Jina team has added their models to the registry, you can find them on their user profile: https://ollama.com/jina. 👍

**Comment by JoanFM** [comment]
> > it would be great if paraphrase-multilingual-MiniLM-L12-v2 will be supported
> 
> One user has uploaded it to the registry already: https://ollama.com/nextfire/paraphrase-multilingual-minilm, haven't tested it so I cannot speak on its performance.

Hey @thinkverse,

We still need a new release for these to work. Do you know when the next release will be?

**Comment by gevzak** [comment]
Seems like jinaai/jina-embeddings-v2-base-de works since the latest Ollama version, but intfloat/multilingual-e5-large-instruct support is still missing in llama.cpp

**Comment by dcasota** [comment]
@wouterverduin for Dutch language support in an Ollama installation, you might use `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`.

Here a list with the LLMs mentioned in this thread.

```
                  Embeddings LLM                             |   in Ollama hub?                                   | architecture | manual import (via gguf)?       | Dutch language ?
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
intfloat/multilingual-e5-large-instruct                      |    no                                              | xlm-roberta  |           ?                      |        yes
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
jinaai/jina-embeddings-v2-base-de	                     |    yes                                             | bert         |   (not necessary anymore)        |        no
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2  |    yes(nextfire/paraphrase-multilingual-minilm)    | bert         | (yes, but not necessary anymore) |        yes
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sentence-transformers/all-MiniLM-L6-v2                       |    yes(chroma/.. and tazarov/..)                   | bert         | (yes, but not necessary)         |        no
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
mixedbread-ai/mxbai-embed-large-v1                           |    no                                              | bert         |            ?                     |        no
```

Some information:
- The easiest way in Ollama is that a model supports the language preferred and the task goal.
   If this is not the case, you can try to extend Ollama, but there are limitations. The main limitation is the architecture. Ollama supports 'bert' as Natural Language Processing model. That said, how to find a model with this architecture?

- The HuggingFace hub is the biggest hub with over 700K models. The github repo https://github.com/huggingface has dramatically increased over the last months to provide an enriched portfolio of rich features from science work.
- First, accordingly to https://huggingface.co/models?language=nl&sort=downloads, to find an easy interoperable LLM for Ollama, start in 'Filter by name' with a known LLM (`sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`), select it and select its architecture. In this case 'bert'. With this filter, 47571 models are counted.
  This workaround seems necessary because a direct filter criteria 'bert' in the filter section 'Other' doesn't work.
- Then, go to the 'Languages' filter, and select 'Dutch'. With that additional filter, 86 models counted.
   Here the extract, sorted by 'Trending'

   ![image](https://github.com/ollama/ollama/assets/14890243/7b346944-a840-4343-8d34-b5474f456a9f)

- The Huggingface portal supports task goal filters in 'Natural Language processing'. There is choice e.g. "Sentence Similarity', 'Text Generation', 'Feature extraction', etc.
  E.g. `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2` is in the category 'Sentence Similarity',
  `google-bert/bert-base-multilingual-uncased` is in the category 'Fill-Mask', `nlptown/bert-base-multilingual-uncased-sentiment` is in the category 'Text classification', etc.
- There is a chance that these filtered bert models can be used in Ollama by manual import, see https://github.com/ollama/ollama/issues/3747#issuecomment-2134070860.

  Hope this helps.

**Comment by Kraego** [comment]
> Seems like jinaai/jina-embeddings-v2-base-de works since the latest Ollama version, but intfloat/multilingual-e5-large-instruct support is still missing in llama.cpp

Can confirm this, working with: `ollama:0.1.43`

**Comment by hasansalimkanmaz** [comment]
@wouterverduin You can run a bunch of multilingual models in GGUF format directly with Ollama thanks to [this new integration](https://huggingface.co/docs/hub/en/ollama) between Ollama and HF.

**Comment by dcasota** [comment]
@hasansalimkanmaz this is great news. It is a open-source game changer and brings together LLM scientists and business adopters introducing, monitoring and evaluating their custom solution. Hopefully we will see a bunch of success stories.
