### ISSUE TITLE
Server error when submitting a request through OpenAI client

### ISSUE THREAD

**Issue by mishushakov** [ollama/ollama#3824]
### What is the issue?

Using Vercel AI SDK and llama2

Request:

```ts
const content = [
    { type: 'text', text: prompt },
    { type: 'text', text: page.content },
 ]

const result = await experimental_generateObject({
    model,
    schema,
    messages: [{ role: 'user', content }],
    temperature,
  })
```

Response:

```
mish@Mishs-MBP llm-scraper % bun examples/hn.ts                                                            
12 |     statusCode === 429 || // too many requests
13 |     statusCode >= 500),
14 |     // server error
15 |     data
16 |   }) {
17 |     super(message);
         ^
AI_APICallError: json: cannot unmarshal array into Go struct field Message.messages.content of type string
 url: "http://127.0.0.1:11434/v1/chat/completions"

      at new APICallError (/Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider/dist/index.mjs:17:5)
      at /Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider-utils/dist/index.mjs:279:12
12 |     statusCode === 429 || // too many requests
13 |     statusCode >= 500),
14 |     // server error
15 |     data
16 |   }) {
17 |     super(message);
         ^
AI_APICallError: json: cannot unmarshal array into Go struct field Message.messages.content of type string
 url: "http://127.0.0.1:11434/v1/chat/completions"

      at new APICallError (/Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider/dist/index.mjs:17:5)
      at /Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider-utils/dist/index.mjs:279:12
```

Possibly related to #3690?

### OS

macOS

### GPU

Apple

### CPU

Apple

### Ollama version

0.1.32

**Comment by thinkverse** [comment]
Ollama's OpenAI compatibility doesn't support content arrays, only text contents, you can read about the supported request fields in the documentation: https://github.com/ollama/ollama/blob/main/docs/openai.md#supported-request-fields.

If you want to send more messages, you must send them separately.

```json
[
    {
        "role": "system",
        "content": "You are a helpful assistant."
    },
    {
        "role": "user",
        "content": "Hello!"
    }
]
```

**Comment by mishushakov** [comment]
Alright, will keep that in mind 😉

**Comment by mishushakov** [comment]
I'm getting this now:

```
mish@Mishs-MBP llm-scraper % bun examples/hn.ts
12 |     statusCode === 429 || // too many requests
13 |     statusCode >= 500),
14 |     // server error
15 |     data
16 |   }) {
17 |     super(message);
         ^
AI_APICallError: json: cannot unmarshal array into Go struct field Message.messages.content of type string
 url: "http://127.0.0.1:11434/v1/chat/completions"

      at new APICallError (/Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider/dist/index.mjs:17:5)
      at /Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider-utils/dist/index.mjs:279:12
12 |     statusCode === 429 || // too many requests
13 |     statusCode >= 500),
14 |     // server error
15 |     data
16 |   }) {
17 |     super(message);
         ^
AI_APICallError: json: cannot unmarshal array into Go struct field Message.messages.content of type string
 url: "http://127.0.0.1:11434/v1/chat/completions"

      at new APICallError (/Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider/dist/index.mjs:17:5)
      at /Users/mish/Documents/Projects/llm-scraper/node_modules/@ai-sdk/provider-utils/dist/index.mjs:279:12
```

**Comment by thinkverse** [comment]
From what I understand of Vercel AI SDK, it seems they convert `messages.content` into an array behind the scenes in the [convertToLanguageModelPrompt](https://github.com/vercel/ai/blob/c056579a34a7f71ebce87f0f83c3fc3da20e0a8e/packages/core/core/prompt/convert-to-language-model-prompt.ts#L11) function.

For instance, [the if-statement on line 34](https://github.com/vercel/ai/blob/c056579a34a7f71ebce87f0f83c3fc3da20e0a8e/packages/core/core/prompt/convert-to-language-model-prompt.ts#L34-L39) checks if the `messages.content` is a string, and if it is it'll convert it to an array.

Given that Ollama's OpenAI compatibility doesn't support that yet, Vercel's AI Core sadly isn't compatible either.

**Comment by mishushakov** [comment]
I have started an issue there too. Since this is not an issue with Ollama per se., I'm closing.
Thank you for all your help 😄

**Comment by MaxLeiter** [comment]
I believe https://github.com/ollama/ollama/pull/2506 would fix this, along with improving overall OpenAI compatibility.

**Comment by mishushakov** [comment]
Glad to hear that!
