### ISSUE TITLE
On Windows , with version 0.1.33 assembling two models creates a path error. Version 0.1.32 works correctly.

### ISSUE THREAD

**Issue by amonpaike** [ollama/ollama#4158]
### What is the issue?

On Windows with version 0.1.33 assembling two models creates a path error. 
Version 0.1.32 works correctly.
You can manifest the bug by assembling this model: (there is also the modelfile for ollama) [llava-llama-3-8b-v1_1-gguf](https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/tree/main)

```
FROM ./llava-llama-3-8b-v1_1-int4.gguf
FROM ./llava-llama-3-8b-v1_1-mmproj-f16.gguf
TEMPLATE """{{ if .System }}<|start_header_id|>system<|end_header_id|>

{{ .System }}<|eot_id|>{{ end }}{{ if .Prompt }}<|start_header_id|>user<|end_header_id|>

{{ .Prompt }}<|eot_id|>{{ end }}<|start_header_id|>assistant<|end_header_id|>

{{ .Response }}<|eot_id|>"""
PARAMETER stop "<|start_header_id|>"
PARAMETER stop "<|end_header_id|>"
PARAMETER stop "<|eot_id|>"
PARAMETER num_keep 4
PARAMETER num_ctx 4096


```

I'm reporting a slightly different example because it's the second time the bug has appeared and I decided to report it as it reappeared.
```
ollama create LLava3_nvidia -f Llava_Llama3_Nvidia_ChatQ1_5_Q5.txt

transferring model data
panic: regexp: Compile(`(?im)^(from)\s+D:\AI_APPS\Llama3-ChatQA-1.5-8B.Q5_K_M.gguf\s*$`): error parsing regexp: invalid escape sequence: `\L`

goroutine 1 [running]:
regexp.MustCompile({0xc000391880, 0x3e})
        regexp/regexp.go:317 +0xb4
github.com/ollama/ollama/cmd.CreateHandler(0xc000451208, {0xc0006f45d0, 0x1, 0x1a3aa63?})
        github.com/ollama/ollama/cmd/cmd.go:122 +0x839
github.com/spf13/cobra.(*Command).execute(0xc000451208, {0xc0006f4570, 0x3, 0x3})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc000450f08)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.7.0/command.go:985
main.main()
        github.com/ollama/ollama/main.go:11 +0x4d

```

### OS

Windows

### GPU

Nvidia

### Ollama version

0.1.33

**Comment by mxyng** [comment]
This should be fixed in the next release by #3892
