### ISSUE TITLE
Failure to push llama3 and mistral:0.3 with custom parameters to ollama model registry

### ISSUE THREAD

**Issue by fabceolin** [ollama/ollama#4635]
### What is the issue?
The ollama is failing to push images to ollama model registry for llama3 and mistral v0.3

```
ollama --version
ollama version is 0.1.38
```

commands to reproduce 
```
ollama pull llama3:instruct
cat <<EOF >Modelfile
FROM llama3:instruct
# Set parameters
PARAMETER temperature 0.8
PARAMETER stop Result
SYSTEM """"""
EOF
ollama create -f Modelfile fabceolin/llama3
ollama push fabceolin/llama3
```

local server logs
```
May 25 11:17:06 dev ollama[11383]: [GIN] 2024/05/25 - 11:17:06 | 200 |      54.814µs |       127.0.0.1 | HEAD     "/"
May 25 11:17:06 dev ollama[11383]: [GIN] 2024/05/25 - 11:17:06 | 200 |    1.419569ms |       127.0.0.1 | GET      "/api/tags"
May 25 11:17:37 dev ollama[11383]: [GIN] 2024/05/25 - 11:17:37 | 200 |      19.142µs |       127.0.0.1 | HEAD     "/"
May 25 11:17:43 dev ollama[11383]: panic: runtime error: index out of range [0] with length 0
May 25 11:17:43 dev ollama[11383]: goroutine 23 [running]:
May 25 11:17:43 dev ollama[11383]: github.com/ollama/ollama/server.(*blobUpload).Prepare(0xc0006000e0, {0x12083a20, 0xc0005b00f0}, 0xc00040e990, 0xc00060e240)
May 25 11:17:43 dev ollama[11383]:         github.com/ollama/ollama/server/upload.go:109 +0x9e5
May 25 11:17:43 dev ollama[11383]: github.com/ollama/ollama/server.uploadBlob({0x12083a20, 0xc0005b00f0}, {{0x1256213, 0x5}, {0x1269913, 0x12}, {0xc0005b6030, 0x9}, {0xc0005b603a, 0x6}, ...}, ...)
May 25 11:17:43 dev ollama[11383]:         github.com/ollama/ollama/server/upload.go:389 +0x6cd
May 25 11:17:43 dev ollama[11383]: github.com/ollama/ollama/server.PushModel({0x12083a20, 0xc0005b00f0}, {0xc0005b6030?, 0x4ca0000045a?}, 0xc00060e240, 0xc000045f88)
May 25 11:17:43 dev ollama[11383]:         github.com/ollama/ollama/server/images.go:799 +0x37c
May 25 11:17:43 dev ollama[11383]: github.com/ollama/ollama/server.(*Server).PushModelHandler.func1()
May 25 11:17:43 dev ollama[11383]:         github.com/ollama/ollama/server/routes.go:496 +0x12b
May 25 11:17:43 dev ollama[11383]: created by github.com/ollama/ollama/server.(*Server).PushModelHandler in goroutine 21
May 25 11:17:43 dev ollama[11383]:         github.com/ollama/ollama/server/routes.go:483 +0x186
May 25 11:17:43 dev systemd[1]: ollama.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 25 11:17:43 dev systemd[1]: ollama.service: Failed with result 'exit-code'.
May 25 11:17:43 dev systemd[1]: ollama.service: Consumed 5.298s CPU time.
```

I had the same issue with mistral version v0.3 instruct.

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.38

**Comment by jimscard** [comment]
You didn't specify any tags on the CLI.  What happens if you do a `ollama push fabceolin/llama3:instruct` or `ollama push fabceolin/llama3:latest` ?

**Comment by fabceolin** [comment]
Same error with 
```
ollama push fabceolin/llama3:instruct
```
and
```
ollama push fabceolin/llama3:latest
```

With llama2, the push is done correctly.

**Comment by bmizerany** [comment]
@fabceolin If you upgrade to the latest version (0.3.10 at the time of writing) does the issue persist?

**Comment by pdevine** [comment]
@fabceolin sorry for the slow response. It looks like you were able to create the llama3 model repo on ollama.com, but nothing got pushed to it.

**Comment by pdevine** [comment]
I'm going to go ahead and close this, but we can reopen it if it's still a problem (and apologies for the slow response!)
