### ISSUE TITLE
I encountered this error when converting the Tongyi-Finance-14B-Chat-Int4-AWQ model

### ISSUE THREAD

**Issue by wangkai111111** [ollama/ollama#4823]
### What is the issue?

`(.venv) [root@bastion ollama]# python llm/llama.cpp/convert-hf-to-gguf.py ./model  --outtype f16 --outfile converted.bin
INFO:hf-to-gguf:Loading model: model
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:Set model tokenizer
Traceback (most recent call last):
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2865, in <module>
    main()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2850, in main
    model_instance.set_vocab()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 1592, in set_vocab
    self._set_vocab_qwen()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 530, in _set_vocab_qwen
    assert len(merged) == 2
AssertionError
`

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.41

**Comment by wangkai111111** [comment]
I changed`len(merged) == 2`to`len(merged) >= 2`This error appeared again. Please help.

`(.venv) [root@bastion ollama]# python llm/llama.cpp/convert-hf-to-gguf.py ./model  --outtype f16 --outfile converted.bin

INFO:hf-to-gguf:Loading model: model
INFO:gguf.gguf_writer:gguf: This GGUF file is for Little Endian only
INFO:hf-to-gguf:Set model parameters
INFO:hf-to-gguf:Set model tokenizer
INFO:gguf.vocab:Adding 153463 merge(s).
INFO:gguf.vocab:Setting special token type bos to 153719
INFO:gguf.vocab:Setting special token type eos to 153719
INFO:gguf.vocab:Setting special token type unk to 153719
INFO:hf-to-gguf:Exporting model to 'converted.bin'
INFO:hf-to-gguf:gguf: loading model part 'model.safetensors'
INFO:hf-to-gguf:output.weight,               torch.bfloat16 --> F16, shape = {5120, 154112}
INFO:hf-to-gguf:blk.0.attn_qkv.bias,         torch.float16 --> F32, shape = {15360}
Traceback (most recent call last):
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2865, in <module>
    main()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 2859, in main
    model_instance.write()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 325, in write
    self.write_tensors()
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 262, in write_tensors
    for new_name, data in ((n, d.squeeze().numpy()) for n, d in self.modify_tensors(data_torch, name, bid)):
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 229, in modify_tensors
    return [(self.map_tensor_name(name), data_torch)]
  File "/root/model/ollama/llm/llama.cpp/convert-hf-to-gguf.py", line 180, in map_tensor_name
    raise ValueError(f"Can not map tensor {name!r}")
ValueError: Can not map tensor 'transformer.h.0.attn.c_attn.qweight'
`

**Comment by pdevine** [comment]
@wangkai111111 I don't recognize that tensor name, so I'm not sure that architecture is supported. You may want to check w/ the llama.cpp folks to see if they are planning to support it.
