### ISSUE TITLE
model import to Ollama

### ISSUE THREAD

**Issue by fingerfree77** [ollama/ollama#4830]
Is it possible to import model to Ollama from HuggingFace which is not listed in the script convert-hf-to-gguf.py?
In my case model:  https://huggingface.co/ai-forever/ruGPT-3.5-13B
When I try import got error:
```
Traceback (most recent call last):
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 2865, in <module>
    main()
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 2850, in main
    model_instance.set_vocab()
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 114, in set_vocab
    self._set_vocab_gpt2()
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 500, in _set_vocab_gpt2
    tokens, toktypes, tokpre = self.get_vocab_base()
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 379, in get_vocab_base
    tokpre = self.get_vocab_base_pre(tokenizer)
  File "llm/llama.cpp/convert-hf-to-gguf.py", line 491, in get_vocab_base_pre
    raise NotImplementedError("BPE pre-tokenizer was not recognized - update get_vocab_base_pre()")
NotImplementedError: BPE pre-tokenizer was not recognized - update get_vocab_base_pre()
```

**Comment by sealad886** [comment]
The short answer is no. Ollama relies on the llama.cpp backend to serve the API. Open up an [enhancement request](https://github.com/ggerganov/llama.cpp/issues/new/choose) on the llama.cpp project, or (even better!) see if you can add the pre-tokenizer yourself and open up a pull request!

**Comment by DewiarQR** [comment]
I would like to know if there has already been any progress in this direction?

**Comment by jmorganca** [comment]
Closing for https://github.com/ollama/ollama/issues/1285 – thanks for the issue!
