### ISSUE TITLE
ollama run qwen2:72b-instruct-q2_K but Error: llama runner process has terminated: signal: aborted (core dumped) 

### ISSUE THREAD

**Issue by mikestut** [ollama/ollama#4964]
### What is the issue?

6月 11 01:17:54 Venue-vPro ollama[2760]: time=2024-06-11T01:17:54.332+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_vocab: special tokens cache size = 421
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_vocab: token to piece cache size = 1.8703 MB
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: format           = GGUF V3 (latest)
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: arch             = qwen2
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: vocab type       = BPE
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_vocab          = 152064
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_merges         = 151387
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_ctx_train      = 32768
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_embd           = 8192
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_head           = 64
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_head_kv        = 8
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_layer          = 80
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_rot            = 128
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_embd_head_k    = 128
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_embd_head_v    = 128
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_gqa            = 8
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_embd_k_gqa     = 1024
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_embd_v_gqa     = 1024
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: f_norm_eps       = 0.0e+00
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: f_clamp_kqv      = 0.0e+00
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: f_max_alibi_bias = 0.0e+00
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: f_logit_scale    = 0.0e+00
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_ff             = 29568
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_expert         = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_expert_used    = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: causal attn      = 1
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: pooling type     = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: rope type        = 2
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: rope scaling     = linear
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: freq_base_train  = 1000000.0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: freq_scale_train = 1
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: n_yarn_orig_ctx  = 32768
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: rope_finetuned   = unknown
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: ssm_d_conv       = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: ssm_d_inner      = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: ssm_d_state      = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: ssm_dt_rank      = 0
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: model type       = 70B
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: model ftype      = Q2_K - Medium
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: model params     = 72.71 B
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: model size       = 27.76 GiB (3.28 BPW)
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: general.name     = Qwen2-72B-Instruct
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: LF token         = 148848 'ÄĬ'
6月 11 01:17:54 Venue-vPro ollama[2760]: llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
6月 11 01:17:54 Venue-vPro ollama[2760]: ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   yes
6月 11 01:17:54 Venue-vPro ollama[2760]: ggml_cuda_init: CUDA_USE_TENSOR_CORES: no
6月 11 01:17:54 Venue-vPro ollama[2760]: ggml_cuda_init: found 2 CUDA devices:
6月 11 01:17:54 Venue-vPro ollama[2760]:   Device 0: Tesla M40 24GB, compute capability 5.2, VMM: yes
6月 11 01:17:54 Venue-vPro ollama[2760]:   Device 1: Tesla M40 24GB, compute capability 5.2, VMM: yes
6月 11 01:17:55 Venue-vPro ollama[2760]: llm_load_tensors: ggml ctx size =    1.38 MiB
6月 11 01:17:55 Venue-vPro ollama[2760]: time=2024-06-11T01:17:55.789+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:17:56 Venue-vPro ollama[2760]: time=2024-06-11T01:17:56.152+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors: offloading 80 repeating layers to GPU
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors: offloading non-repeating layers to GPU
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors: offloaded 81/81 layers to GPU
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors:        CPU buffer size =   389.81 MiB
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors:      CUDA0 buffer size = 13868.58 MiB
6月 11 01:17:56 Venue-vPro ollama[2760]: llm_load_tensors:      CUDA1 buffer size = 14166.62 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: time=2024-06-11T01:18:00.123+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: n_ctx      = 2048
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: n_batch    = 512
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: n_ubatch   = 512
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: flash_attn = 0
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: freq_base  = 1000000.0
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: freq_scale = 1
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_kv_cache_init:      CUDA0 KV buffer size =   328.00 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_kv_cache_init:      CUDA1 KV buffer size =   312.00 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: KV self size  =  640.00 MiB, K (f16):  320.00 MiB, V (f16):  320.00 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model:  CUDA_Host  output buffer size =     0.61 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model:      CUDA0 compute buffer size =   400.01 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model:      CUDA1 compute buffer size =   400.02 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model:  CUDA_Host compute buffer size =    32.02 MiB
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: graph nodes  = 2806
6月 11 01:18:00 Venue-vPro ollama[2760]: llama_new_context_with_model: graph splits = 3
6月 11 01:18:00 Venue-vPro ollama[2760]: time=2024-06-11T01:18:00.374+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:18:04 Venue-vPro ollama[2760]: GGML_ASSERT: /go/src/github.com/ollama/ollama/llm/llama.cpp/ggml-cuda/dmmv.cu:653: false
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2814]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2815]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2816]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2817]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2818]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2819]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2820]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2821]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2822]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2823]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2824]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2825]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2826]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2827]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2828]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2829]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2830]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2831]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2832]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2833]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2834]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2835]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2836]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2837]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2838]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2839]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2840]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2841]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2842]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2843]
6月 11 01:18:04 Venue-vPro ollama[2849]: [New LWP 2844]
6月 11 01:18:04 Venue-vPro ollama[2849]: [Thread debugging using libthread_db enabled]
6月 11 01:18:04 Venue-vPro ollama[2849]: Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
6月 11 01:18:05 Venue-vPro ollama[2760]: time=2024-06-11T01:18:05.095+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:18:05 Venue-vPro ollama[2849]: 0x00007f4b23780c7f in __GI___wait4 (pid=2849, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
6月 11 01:18:05 Venue-vPro ollama[2760]: 27        ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
6月 11 01:18:05 Venue-vPro ollama[2849]: #0  0x00007f4b23780c7f in __GI___wait4 (pid=2849, stat_loc=0x0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.>
6月 11 01:18:05 Venue-vPro ollama[2849]: 27        in ../sysdeps/unix/sysv/linux/wait4.c
6月 11 01:18:05 Venue-vPro ollama[2849]: #1  0x00000000005febbb in ggml_print_backtrace ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #2  0x00000000006b5dbc in ggml_cuda_op_dequantize_mul_mat_vec(ggml_backend_cuda_context&, ggml_tensor const*, ggml_tensor >
6月 11 01:18:05 Venue-vPro ollama[2849]: #3  0x000000000068356a in ggml_cuda_op_mul_mat(ggml_backend_cuda_context&, ggml_tensor const*, ggml_tensor const*, ggml_te>
6月 11 01:18:05 Venue-vPro ollama[2849]: #4  0x00000000006866db in ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #5  0x000000000064a42b in ggml_backend_sched_graph_compute_async ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #6  0x000000000055c91f in llama_decode ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #7  0x00000000004ffbe4 in llama_init_from_gpt_params(gpt_params&) ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #8  0x00000000004a158d in llama_server_context::load_model(gpt_params const&) ()
6月 11 01:18:05 Venue-vPro ollama[2849]: #9  0x0000000000432ed6 in main ()
6月 11 01:18:05 Venue-vPro ollama[2849]: [Inferior 1 (process 2813) detached]
6月 11 01:18:05 Venue-vPro ollama[2760]: time=2024-06-11T01:18:05.395+08:00 level=INFO source=server.go:567 msg="waiting for server to become available" status="ll>
6月 11 01:18:05 Venue-vPro ollama[2760]: time=2024-06-11T01:18:05.646+08:00 level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner pr>
6月 11 01:18:05 Venue-vPro ollama[2760]: [GIN] 2024/06/11 - 01:18:05 | 500 | 13.241382363s |       127.0.0.1 | POST     "/api/chat"
6月 11 01:18:10 Venue-vPro ollama[2760]: time=2024-06-11T01:18:10.885+08:00 level=WARN source=sched.go:511 msg="gpu VRAM usage didn't recover within timeout" secon>
6月 11 01:18:11 Venue-vPro ollama[2760]: time=2024-06-11T01:18:11.134+08:00 level=WARN source=sched.go:511 msg="gpu VRAM usage didn't recover within timeout" secon>
6月 11 01:18:11 Venue-vPro ollama[2760]: time=2024-06-11T01:18:11.385+08:00 level=WARN source=sched.go:511 msg="gpu VRAM usage didn't recover within timeout" secon>

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.1.42

**Comment by littlecc9999** [comment]
I have the same problem with qwen2:7b

**Comment by mikestut** [comment]
I can run the model qwen7b:16bf Maybe you can try it.



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 11, 2024 14:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ollama/ollama] ollama run qwen2:72b-instruct-q2_K but Error:llama runner process has terminated: signal: aborted (core dumped)  (Issue#4964)




 
I have the same problem with qwen2:7b

**Comment by wgong** [comment]
got the same error when running CLI
```
$ ollama run qwen2
Error: llama runner process has terminated: signal: aborted (core dumped)
```

**Comment by YogaNovvaindra** [comment]
Got the same error running phi3 on ollama docker CPU only
```
root@0fe89d3262cb:/# ollama run phi3
Error: llama runner process has terminated: signal: aborted (core dumped) 
root@0fe89d3262cb:/# ollama -v
ollama version is 0.1.44
```

Log:

```
llama_model_load: error loading model: mmap failed: No such device
llama_load_model_from_file: exception loading model
terminate called after throwing an instance of 'std::runtime_error'
  what():  mmap failed: No such device
time=2024-06-14T02:16:51.468Z level=INFO source=server.go:567 msg="waiting for server to become available" status="llm server error"
time=2024-06-14T02:16:51.719Z level=ERROR source=sched.go:344 msg="error loading llama server" error="llama runner process has terminated: signal: aborted (core dumped) "
```

**Comment by lyx8995** [comment]
same problem，have you handled？

**Comment by nicho2** [comment]
hello, i have the same problem with camembert-large embedding model (latest or q8). I use an another model (nomic embed text) without problem:


    POST /api/embeddings HTTP/1.1
    host: 172.17.0.1:11434
    connection: keep-alive
    content-type: text/plain;charset=UTF-8
    accept: */*
    accept-language: *
    sec-fetch-mode: cors
    user-agent: node
    accept-encoding: gzip, deflate
    content-length: 623
    
    {"model":"royalpha/sentence-camembert-large:latest","prompt":"<document_metadata>\nsourceDocument: Guide technique AREA MANAGER - partie 1.md\npublished: 7/1/2024, 6:44:11 AM\n</document_metadata>\n\n# Guide Technique Note - Guide Area Manager.Docx Alain Sabourdy 20 Juin 2024\r\n\r\n## Contexte\r\n\r\n![0_Image_0.Png](0_Image_0.Png)\r\n\r\nCe document est r..dig.. dans l'unique objectif d'..tre une source d'information pour notre d..veloppement autour d'une Intelligence artificielle d'assistance au commissionnement d'un BMS IoT. Il doit ..tre traduit au format \"markdown\" pour ..tre communiqu.. .. l'IA Attention,"}HTTP/1.1 500 Internal Server Error
    Content-Type: application/json; charset=utf-8
    Date: Mon, 01 Jul 2024 08:00:04 GMT
    Content-Length: 79
    
    {"error":"llama runner process has terminated: signal: aborted (core dumped) "}



I use the version 0.1.48
i'm on Ubuntu with 2 GPU (A4000)
