### ISSUE TITLE
"llama3.1:70b does not support tools"

### ISSUE THREAD

**Issue by SinanAkkoyun** [ollama/ollama#5967]
### What is the issue?

```
Traceback (most recent call last):
  File "/home/ai/ml/llm/inference/ollama/function_calling.py", line 3, in <module>
    response = ollama.chat(
               ^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/ollama/lib/python3.11/site-packages/ollama/_client.py", line 235, in chat
    return self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/ollama/lib/python3.11/site-packages/ollama/_client.py", line 98, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ai/.mconda3/envs/ollama/lib/python3.11/site-packages/ollama/_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: llama3.1:70b does not support tools

```

Solution: Add support for all sub tags

### OS

Linux

### GPU

Nvidia

### CPU

Intel

### Ollama version

0.3.0

**Comment by rick-github** [comment]
The initial release of the llama3.1 models didn't have a template that supported tools, if you re-pull it you should get the update.

**Comment by StarPet** [comment]
Is there a property of the model (e.g. via /show API) which tells if the model supports tools?

**Comment by rick-github** [comment]
Not yet, there is an open ticket: https://github.com/ollama/ollama/issues/5794

**Comment by SinanAkkoyun** [comment]
@rick-github Thank you so much!
