### ISSUE TITLE
I can not connect to 11434 port

### ISSUE THREAD

**Issue by 1760842797** [ollama/ollama#8154]
### What is the issue?

sir, i add Environment="OLLAMA_HOST=0.0.0.0" to the service file,Then i restart  ollama. now, i find the service listener port is only have tcp6，without tcp4 listen，so i can not access to the service from other machine. how can i fix this problem？  thank you

[root@localhost ollama]#  netstat -tuln | grep 11434
tcp6       0      0 :::11434                :::*                    LISTEN
[root@localhost ollama]#

**Comment by pdevine** [comment]
Can you post your server logs (particularly the top part of the logs). Details on how to get the logs are [here](https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md).

**Comment by UsefullProgrammer** [comment]
Same error log:
```
2025-03-12 09:43:19 cheshire_cat_core  | HumanMessage
2025-03-12 09:43:19 cheshire_cat_core  | test
2025-03-12 09:43:19 cheshire_cat_core  | ========================================
2025-03-12 09:43:19 cheshire_cat_core  | ERROR: [Errno 111] Connection refused
2025-03-12 09:43:19 cheshire_cat_core  | Traceback (most recent call last):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2025-03-12 09:43:19 cheshire_cat_core  |     yield
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     resp = self._pool.handle_request(req)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     raise exc from None
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     response = connection.handle_request(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     raise exc
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     stream = self._connect(request)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
2025-03-12 09:43:19 cheshire_cat_core  |     stream = self._network_backend.connect_tcp(**kwargs)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
2025-03-12 09:43:19 cheshire_cat_core  |     with map_exceptions(exc_map):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2025-03-12 09:43:19 cheshire_cat_core  |     self.gen.throw(typ, value, traceback)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2025-03-12 09:43:19 cheshire_cat_core  |     raise to_exc(exc) from exc
2025-03-12 09:43:19 cheshire_cat_core  | httpcore.ConnectError: [Errno 111] Connection refused
2025-03-12 09:43:19 cheshire_cat_core  | 
2025-03-12 09:43:19 cheshire_cat_core  | The above exception was the direct cause of the following exception:
2025-03-12 09:43:19 cheshire_cat_core  | 
2025-03-12 09:43:19 cheshire_cat_core  | Traceback (most recent call last):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/app/cat/looking_glass/stray_cat.py", line 506, in __call__
2025-03-12 09:43:19 cheshire_cat_core  |     agent_output: AgentOutput = self.main_agent.execute(self)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/app/cat/agents/main_agent.py", line 76, in execute
2025-03-12 09:43:19 cheshire_cat_core  |     memory_agent_out : AgentOutput = memory_agent.execute(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/app/cat/agents/memory_agent.py", line 39, in execute
2025-03-12 09:43:19 cheshire_cat_core  |     output = chain.invoke(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/runnables/base.py", line 2879, in invoke
2025-03-12 09:43:19 cheshire_cat_core  |     input = context.run(step.invoke, input, config)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 277, in invoke
2025-03-12 09:43:19 cheshire_cat_core  |     self.generate_prompt(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 777, in generate_prompt
2025-03-12 09:43:19 cheshire_cat_core  |     return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 634, in generate
2025-03-12 09:43:19 cheshire_cat_core  |     raise e
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 624, in generate
2025-03-12 09:43:19 cheshire_cat_core  |     self._generate_with_cache(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 846, in _generate_with_cache
2025-03-12 09:43:19 cheshire_cat_core  |     result = self._generate(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_ollama/chat_models.py", line 642, in _generate
2025-03-12 09:43:19 cheshire_cat_core  |     final_chunk = self._chat_stream_with_aggregation(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_ollama/chat_models.py", line 543, in _chat_stream_with_aggregation
2025-03-12 09:43:19 cheshire_cat_core  |     for stream_resp in self._create_chat_stream(messages, stop, **kwargs):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/langchain_ollama/chat_models.py", line 525, in _create_chat_stream
2025-03-12 09:43:19 cheshire_cat_core  |     yield from self._client.chat(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 80, in _stream
2025-03-12 09:43:19 cheshire_cat_core  |     with self._client.stream(method, url, **kwargs) as r:
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
2025-03-12 09:43:19 cheshire_cat_core  |     return next(self.gen)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 880, in stream
2025-03-12 09:43:19 cheshire_cat_core  |     response = self.send(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
2025-03-12 09:43:19 cheshire_cat_core  |     response = self._send_handling_auth(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
2025-03-12 09:43:19 cheshire_cat_core  |     response = self._send_handling_redirects(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
2025-03-12 09:43:19 cheshire_cat_core  |     response = self._send_single_request(request)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
2025-03-12 09:43:19 cheshire_cat_core  |     response = transport.handle_request(request)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     with map_httpcore_exceptions():
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2025-03-12 09:43:19 cheshire_cat_core  |     self.gen.throw(typ, value, traceback)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
2025-03-12 09:43:19 cheshire_cat_core  |     raise mapped_exc(message) from exc
2025-03-12 09:43:19 cheshire_cat_core  | httpx.ConnectError: [Errno 111] Connection refused
2025-03-12 09:43:19 cheshire_cat_core  | ERROR: ConnectError('[Errno 111] Connection refused')
2025-03-12 09:43:19 cheshire_cat_core  | Traceback (most recent call last):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
2025-03-12 09:43:19 cheshire_cat_core  |     yield
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     resp = self._pool.handle_request(req)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     raise exc from None
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     response = connection.handle_request(
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     raise exc
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
2025-03-12 09:43:19 cheshire_cat_core  |     stream = self._connect(request)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
2025-03-12 09:43:19 cheshire_cat_core  |     stream = self._network_backend.connect_tcp(**kwargs)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
2025-03-12 09:43:19 cheshire_cat_core  |     with map_exceptions(exc_map):
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2025-03-12 09:43:19 cheshire_cat_core  |     self.gen.throw(typ, value, traceback)
2025-03-12 09:43:19 cheshire_cat_core  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2025-03-12 09:43:19 cheshire_cat_core  |     raise to_exc(exc) from exc
2025-03-12 09:43:19 cheshire_cat_core  | httpcore.ConnectError: [Errno 111] Connection refused
```

**Comment by pdevine** [comment]
Going to close this as stale.
