### ISSUE TITLE
Unexpected Connection Closure and GPU Memory Not Releasing

### ISSUE THREAD

**Issue by BronyaKaslana06** [ollama/ollama#8248]
### Problem Description

I am using Ubuntu 22.04 and making network requests to a local Ollama service with Python to run a series of models sequentially. After each model runs, it is unloaded using the following Python code. However, the task encounters an issue after reaching a certain point, where the Ollama network service unexpectedly stops when loading a model, resulting in the following error:

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/EvalLLM/main.py", line 109, in <module>
    generator.generate_and_save(section)
  File "/root/autodl-tmp/EvalLLM/main.py", line 93, in generate_and_save
    response_text = ollamaCaller.generate_response(prompt=question)
  File "/root/autodl-tmp/EvalLLM/Caller/OllamaCaller.py", line 18, in generate_response
    response = requests.post("http://localhost:11434/api/generate", json=payload)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

This could be caused by the service not responding for a long time, or it might be due to the daemon process being unexpectedly closed, right? At the time of the error, The program was just finished loading a new model, and the Ollama logs are as follows:

```log
time=2024-12-25T22:05:34.725+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/root/autodl-tmp/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa gpu=GPU-30d02008-3980-d577-cd07-7e3fcabf1d31 parallel=4 available=25158156288 required="6.2 GiB"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=server.go:104 msg="system memory" total="377.3 GiB" free="327.5 GiB" free_swap="0 B"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=memory.go:356 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[23.4 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=server.go:376 msg="starting llama server" cmd="/usr/local/lib/ollama/runners/cuda_v12_avx/ollama_llama_server runner --model /root/autodl-tmp/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 112 --parallel 4 --port 41461"
time=2024-12-25T22:05:34.978+08:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-12-25T22:05:34.978+08:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
time=2024-12-25T22:05:34.978+08:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
time=2024-12-25T22:05:35.021+08:00 level=INFO source=runner.go:945 msg="starting go runner"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
time=2024-12-25T22:05:35.029+08:00 level=INFO source=runner.go:946 msg=system info="CUDA : ARCHS = 600,610,620,700,720,750,800,860,870,890,900 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | cgo(gcc)" threads=112
time=2024-12-25T22:05:35.029+08:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:41461"
llama_load_model_from_file: using device CUDA0 (NVIDIA GeForce RTX 3090) - 23992 MiB free
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from /root/autodl-tmp/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
time=2024-12-25T22:05:35.230+08:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server loading model"
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.8000 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: ssm_dt_b_c_rms   = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 4.33 GiB (4.64 BPW) 
llm_load_print_meta: general.name     = Meta-Llama-3-8B-Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128009 '<|eot_id|>'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOG token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading output layer to GPU
llm_load_tensors: offloaded 33/33 layers to GPU
llm_load_tensors:   CPU_Mapped model buffer size =   281.81 MiB
llm_load_tensors:        CUDA0 model buffer size =  4155.99 MiB
llama_new_context_with_model: n_seq_max     = 4
llama_new_context_with_model: n_ctx         = 8192
llama_new_context_with_model: n_ctx_per_seq = 2048
llama_new_context_with_model: n_batch       = 2048
llama_new_context_with_model: n_ubatch      = 512
llama_new_context_with_model: flash_attn    = 0
llama_new_context_with_model: freq_base     = 500000.0
llama_new_context_with_model: freq_scale    = 1
llama_new_context_with_model: n_ctx_per_seq (2048) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
llama_kv_cache_init:      CUDA0 KV buffer size =  1024.00 MiB
llama_new_context_with_model: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     2.02 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   560.00 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    24.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
```

The logs end here.

Regardless of the cause of this issue, after it occurs, about 6GB of GPU memory remains unreleased and cannot be freed even by restarting Ollama. Below is the output of `nvidia-smi`:

```
(base) root@autodl-container-d33848b29e-31b2d2f4:~# nvidia-smi
Thu Dec 26 22:29:15 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.78                 Driver Version: 550.78         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:10:00.0 Off |                  N/A |
| 30%   28C    P8             17W /  350W |    6002MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

Has anyone encountered this issue? How can it be resolved? Thank you! 

### OS

Linux

### GPU

Nvidia

### Ollama version

0.5.4

**Comment by rick-github** [comment]
From the shell prompt, it seems like you are running this in some sort of container.  If that's correct, what's the output of `nvidia-smi` outside of the container?  When the log stops, is the ollama server still running?

**Comment by BronyaKaslana06** [comment]
> From the shell prompt, it seems like you are running this in some sort of container. If that's correct, what's the output of `nvidia-smi` outside of the container? When the log stops, is the ollama server still running?

I am indeed running this in a container, but it's provided by autodl, so it's quite difficult for me to access outside of the container.

I apologize for not checking the status of the Ollama service promptly. However, the Ollama server should still be running as a foreground process at that time by `ps -ef`. After I noticed that the logs had stopped, I immediately executed commands `systemctl restart ollama.service` to try to resolve the issue.

**Comment by rick-github** [comment]
> service not responding for a long time

There are no timeouts on the server side, so the client should log something if a deadline is exceeded.

> daemon process being unexpectedly closed

Yes, but the server (daemon) crashing is rare.  If that were the case, there should be log entries from `systemd`.

There are no indications in your log of an API call.  If the client timed out, there would be a 500 error in the log.  If the runner crashed, there should be errors in the log.  If the server crashed, `systemd` would normally restart it.  What's the output of `systemctl cat ollama`?

**Comment by BronyaKaslana06** [comment]
> > service not responding for a long time
> 
> There are no timeouts on the server side, so the client should log something if a deadline is exceeded.
> 
> > daemon process being unexpectedly closed
> 
> Yes, but the server (daemon) crashing is rare. If that were the case, there should be log entries from `systemd`.
> 
> There are no indications in your log of an API call. If the client timed out, there would be a 500 error in the log. If the runner crashed, there should be errors in the log. If the server crashed, `systemd` would normally restart it. What's the output of `systemctl cat ollama`?

Thank you, api call and restart log is like the following logs:
```
...
[GIN] 2024/12/25 - 22:04:58 | 200 |  2.909282444s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:01 | 200 |  2.760769467s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:05 | 200 |  4.151066683s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:08 | 200 |  3.562858056s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:19 | 200 | 10.621513776s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:22 | 200 |  3.161121577s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:25 | 200 |  2.756690189s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:28 | 200 |  3.039066957s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:31 | 200 |  3.233472736s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:34 | 200 |  2.553347138s |       127.0.0.1 | POST     "/api/generate"
[GIN] 2024/12/25 - 22:05:34 | 200 |    1.148874ms |       127.0.0.1 | POST     "/api/generate"
time=2024-12-25T22:05:34.725+08:00 level=INFO source=sched.go:714 msg="new model will fit in available VRAM in single GPU, loading" model=/root/autodl-tmp/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa gpu=GPU-30d02008-3980-d577-cd07-7e3fcabf1d31 parallel=4 available=25158156288 required="6.2 GiB"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=server.go:104 msg="system memory" total="377.3 GiB" free="327.5 GiB" free_swap="0 B"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=memory.go:356 msg="offload to cuda" layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[23.4 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.7 GiB" memory.weights.repeating="4.3 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
time=2024-12-25T22:05:34.977+08:00 level=INFO source=server.go:376 msg="starting llama server" cmd="/usr/local/lib/ollama/runners/cuda_v12_avx/ollama_llama_server runner --model /root/autodl-tmp/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 112 --parallel 4 --port 41461"
time=2024-12-25T22:05:34.978+08:00 level=INFO source=sched.go:449 msg="loaded runners" count=1
time=2024-12-25T22:05:34.978+08:00 level=INFO source=server.go:555 msg="waiting for llama runner to start responding"
time=2024-12-25T22:05:34.978+08:00 level=INFO source=server.go:589 msg="waiting for server to become available" status="llm server error"
time=2024-12-25T22:05:35.021+08:00 level=INFO source=runner.go:945 msg="starting go runner"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
time=2024-12-25T22:05:35.029+08:00 level=INFO source=runner.go:946 msg=system info="CUDA : ARCHS = 600,610,620,700,720,750,800,860,870,890,900 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | cgo(gcc)" threads=112
time=2024-12-25T22:05:35.029+08:00 level=INFO source=.:0 msg="Server listening on 127.0.0.1:41461"
llama_load_model_from_file: using device CUDA0 (NVIDIA GeForce RTX 3090) - 23992 MiB free
...
llama_new_context_with_model:  CUDA_Host compute buffer size =    24.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 2
2024/12/26 09:02:12 routes.go:1259: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:false OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/autodl-tmp OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-12-26T09:02:12.802+08:00 level=INFO source=images.go:757 msg="total blobs: 87"
time=2024-12-26T09:02:12.803+08:00 level=INFO source=images.go:764 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
...
```
the output of `systemctl cat ollama` is
```
(base) root@autodl-container-d33848b29e-31b2d2f4:~# systemctl cat ollama
[Unit]
Description=Ollama Service
After=network-online.target

[Service]
ExecStart=/usr/local/bin/ollama serve
User=root
Group=root
Restart=always
RestartSec=3
Environment="PATH=/root/miniconda3/bin:/root/miniconda3/condabin:/root/miniconda3/bin:/usr/local/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"


Environment="OLLAMA_MODELS=/root/autodl-tmp"
Environment="OLLAMA_HOST=0.0.0.0:11434"

[Install]
WantedBy=default.target
```

**Comment by rick-github** [comment]
So far, the logs look pretty normal, with no errors.  Run `systemctl edit ollama` and add `Environment="OLLAMA_DEBUG=1"`, extra debugging may show what's happening.  The `new model` load at 2024-12-25T22:05:34.725 indicates a model or parameter change from the last /api/generate (a surprisingly short one at 1.15ms), but there's no GIN log line to indicate that the new model completed the generation.

**Comment by BronyaKaslana06** [comment]
> So far, the logs look pretty normal, with no errors. Run `systemctl edit ollama` and add `Environment="OLLAMA_DEBUG=1"`, extra debugging may show what's happening. The `new model` load at 2024-12-25T22:05:34.725 indicates a model or parameter change from the last /api/generate (a surprisingly short one at 1.15ms), but there's no GIN log line to indicate that the new model completed the generation.

Thank you for the suggestion. The absence of the GIN log line might be due to the Python script interrupting the connection, causing the program to halt without completing the generation (since I didn’t use a try-catch block).
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/miniconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/EvalLLM/main.py", line 109, in <module>
    generator.generate_and_save(section)
  File "/root/autodl-tmp/EvalLLM/main.py", line 93, in generate_and_save
    response_text = ollamaCaller.generate_response(prompt=question)
  File "/root/autodl-tmp/EvalLLM/Caller/OllamaCaller.py", line 18, in generate_response
    response = requests.post("http://localhost:11434/api/generate", json=payload)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
My python code:
```
class OllamaCaller(BaseCaller):
    # def __init__(self, model_name):
    #     super().__init__(model_name)

    def generate_response(self, prompt):
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,
            "temperature": 0,
        }
        response = requests.post("http://localhost:11434/api/generate", json=payload)
        if response.status_code == 200:
            return response.json().get('response', 'No response field found')
        return f"Error: {response.status_code}, {response.text}"

    def stop_model(self):
        stop_payload = {
            "model": self.model_name,
            "keep_alive": 0
        }
        response = requests.post("http://localhost:11434/api/generate", json=stop_payload)
        return response.json()
```
 I will add Environment="OLLAMA_DEBUG=1" and monitor other execution rounds to see if this issue persists.

**Comment by rick-github** [comment]
Came across this page, leaving it here for reference: https://www.autodl.com/docs/qa4/
